baseURL = "https://www.mas9612.net/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "mas9612's note"
theme = "hugo-future-imperfect"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = true
rssLimit = 10
enableEmoji = true
googleAnalytics = "UA-134133452-1"
preserveTaxonomyNames = true
paginate = 10
disqusShortname = "mas9612s-note"
pluralizeListTitles = false
enableRobotsTXT = true
canonifyURLs = true

[permalinks]
  post = "/posts/:title/"

[author]
  name = "Masato Yamazaki"

[params]
  description          = "About Programming, Computer, Technology..."
  navbarTitle          = "mas9612's note"
  viewMorePostLink     = "/posts/"

  rssAppearAtTop       = true
  socialAppearAtTop    = true

# categoriesByCount    = true
# showSidebarCategories = true
  includeReadingTime   = true

  loadFavicon          = false
  socialShare          = true
  socialShareHatebu    = true
  socialShareTwitter   = true
  socialShareFacebook  = true
  socialShareEmail     = true
  socialShareGoogleplus = false
  socialShareReddit    = false
  socialShareLinkedin  = false
  socialShareStumbleupon = false
  socialSharePinterest = false

  disable_highlight = false
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "css"]
  highlightjsTheme = "github"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

[params.intro]
  header    = "mas9612's note"
  paragraph = "About Programming, Computer, Technology..."

[params.postAmount]
    sidebar = 5

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  identifier = "fa fa-newspaper-o"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  identifier = "fa fa-sitemap"
  weight = 4

# [[menu.main]]
#   name = "Contact"
#   url = "/contact/"
#   identifier = "fa fa-envelope-o"
#   weight = 6

[social]
  github           = "mas9612"
  twitter          = "mas9612"
  facebook         = "mas9612"
  email            = "mas9612@gmail.com"
