version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
        environment:
          TZ: Asia/Tokyo

    working_directory: /go/src/github.com/mas9612/mas9612.net
    steps:
      - checkout

      - run:
          name: Update submodule (Hugo theme)
          command: git submodule update --init --recursive

      - run:
          name: Install hugo
          command: |
            cd /tmp
            curl -LO https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz
            tar xzf hugo_0.54.0_Linux-64bit.tar.gz
            sudo mv hugo /usr/local/bin
            cd /go/src/github.com/mas9612/mas9612.net

      - run:
          name: build HTML
          command: hugo

      - add_ssh_keys:
          fingerprints:
            - "dd:5e:16:e4:9e:d9:fa:f1:be:44:bf:47:8f:43:fa:bb"

      - run:
          name: Set Git config
          command: |
            git config --global user.name "Masato Yamazaki"
            git config --global user.email "mas9612@gmail.com"

      - run:
          name: Clone mas9612.github.io
          command: git clone git@github.com:mas9612/mas9612.github.io.git ~/mas9612.github.io

      - run:
          name: Copy HTML to mas9612.github.io
          command: cp -r ./public/* ~/mas9612.github.io/

      - run:
          name: Commit & Deploy
          command: ./deploy.sh
