version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/mas9612/mas9612.net
    steps:
      - checkout

      - run:
          name: Install hugo
          command: go get -v github.com/gohugoio/hugo

      - run:
          name: build HTML
          command: hugo

      - run:
          name: Clone mas9612.github.io
          command: git clone git@github.com:mas9612/mas9612.github.io.git /go/src/mas9612.github.io

      - run:
          name: Copy HTML to mas9612.github.io
          command: cp -r ./public/* /go/src/mas9612.github.io/

      - run:
          name: Commit & Deploy
          command: |
            cd /go/src/mas9612.github.io
            git commit -m "$(TZ=Asia/Tokyo date "deploy at +%Y%m%dT%T+09:00 from CircleCI")"
            git push origin master
